version: '2.1'
volumes:
    db-data:
    config-data:
services:
trafficdatasys:
    image: opendatacam
    restart: always
    build: .
    privileged: true
    volumes:
      - 'db-data:/data/db'
      - 'config-data:/data/odc'
    ports:
      - "8080:8080"
      - "8070:8070"
      - "8090:8090"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - 'db-data:/data/db'
  node:
    image: "balenalib/jetson-nano-debian-node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8181"
